### ISSUE TITLE
make password server not mandatory

### ISSUE THREAD

**Issue by QuentinJ54** [jsknnr/ark-ascended-server#12]
Hello,

Can you make the server password not mandatory for the container to work?

Thanks

**Comment by jsknnr** [comment]
Sure. Give me a few minutes.

**Comment by QuentinJ54** [comment]
Thanks

**Comment by jsknnr** [comment]
Sorry this change took a bit longer than I wanted. I ended up making some other enhancements to bundle with this change. You can now run the server without a password.
