### ISSUE TITLE
Permission chown -R 10000:10000

### ISSUE THREAD

**Issue by QuentinJ54** [jsknnr/ark-ascended-server#16]
Good morning,

Can you remove the requirement to use the steam user? 
in fact I am on Linux and I want to use another user, so it is impossible to launch the server

**Comment by QuentinJ54** [comment]
In the meantime I use https://github.com/n8maninger/ark-ascended-docker

**Comment by jsknnr** [comment]
The user does not need to exist on your host system. The user and group IDs ideally should also be unique to prevent collision of the host machine, this is security best practice. Can you describe what you are trying to do?

**Comment by QuentinJ54** [comment]
I would like to launch the server with another user but in your configuration this is not possible. but I found a solution thank you.
